### ISSUE TITLE
Solicit feedback on Mocha v2.0.0 pre-releases

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#571]
* [x] @threedaymonk: Ruby v2.7.5; tests OK; deprecation warnings displayed; difficulties diagnosing deprecation warnings addressed in #573
* [x] @h-lame: Ruby v3.1.2; tests OK; deprecation warnings displayed; error due to `reinstate_undocumented_behaviour_from_v1_9` config option addressed in #572
* [x] alphagov/whitehall#6925, freerange/whitehall#3: Ruby v3.1.2; error due to `reinstate_undocumented_behaviour_from_v1_9` config option addressed in #572; demonstrated fix for 18/51 Mocha deprecation warnings in https://github.com/freerange/whitehall/pull/3/commits/0a434c0e2c0cdf3d909a4138c4d619dc038ef02b
* [x] @wasabigeek & @byroot: One of Shopify's biggest repos

**Comment by wasabigeek** [comment]
@floehopper so we've tested the alpha release in one of our biggest repos, and it seems to be working + the warnings can be captured by https://github.com/Shopify/deprecation_toolkit, so I think we're good 👍 (Thanks @byroot for the help). We'll wait for the stable release before integrating it though 😄.

**Comment by floehopper** [comment]
@wasabigeek @byroot Brilliant - thanks so much for doing that and for letting me know. I'll try to get the stable version released early next week.

**Comment by floehopper** [comment]
@wasabigeek I'm afraid there's going to be a bit of a delay on the release due to a family emergency. Hopefully later this week. 🤞
