### ISSUE TITLE
Mocha v2 official release - checklist

### ISSUE THREAD

**Issue by floehopper** [freerange/mocha#575]
- [x] Prepare blog post
- [x] Incorporate relevant changes from v1.16.0, e.g. release notes for v1.16.0!
- [x] Bump version
- [x] Update release notes
- [x] Push release to Rubygems
- [x] Change GH Pages setting to deploy from `main` branch again (https://github.com/freerange/mocha/settings/pages) - do this **before** pushing changes to docs!
- [x] Update docs
- [x] Publish blog post
- [x] Tweet about release - mention Nick Koh's work on the strict keyword argument matching feature

**Comment by floehopper** [comment]
> Incorporate relevant changes from v1.16.0, e.g. release notes for v1.16.0!

Addressed in a5e07fcc1b184089d719e6d706146ce832745324.

**Comment by floehopper** [comment]
All done. Closing! 😅
